# Numpy - Array Manipulation

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,4))

In [4]:
arr

array([[1, 1, 8, 9],
       [1, 3, 6, 4],
       [5, 2, 3, 8]])

In [6]:
arr.reshape(6,2) # changing data into 6X2

array([[1, 1],
       [8, 9],
       [1, 3],
       [6, 4],
       [5, 2],
       [3, 8]])

In [8]:
arr.reshape(2,-2)

array([[1, 1, 8, 9, 1, 3],
       [6, 4, 5, 2, 3, 8]])

In [9]:
arr.T

array([[1, 1, 5],
       [1, 3, 2],
       [8, 6, 3],
       [9, 4, 8]])

In [10]:
arr

array([[1, 1, 8, 9],
       [1, 3, 6, 4],
       [5, 2, 3, 8]])

In [11]:
arr.flatten() # flatten() converts n-dim into 1-dimension.

array([1, 1, 8, 9, 1, 3, 6, 4, 5, 2, 3, 8])

In [12]:
arr1 = np.array([1,2,3,3,4])

In [13]:
arr1.ndim

1

In [15]:
np.expand_dims(arr1,axis=1)  # axis=1 : column and axis=0 : Row

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [16]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 3, 4]])

In [17]:
arr

array([[1, 1, 8, 9],
       [1, 3, 6, 4],
       [5, 2, 3, 8]])

In [18]:
np.squeeze(arr)  # Not working here.

array([[1, 1, 8, 9],
       [1, 3, 6, 4],
       [5, 2, 3, 8]])

In [19]:
data = np.array([[1],[2],[3]])

In [20]:
data

array([[1],
       [2],
       [3]])

In [22]:
np.squeeze(data)  # convert into 1-dimension

array([1, 2, 3])

In [23]:
arr1

array([1, 2, 3, 3, 4])

In [24]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [26]:
np.roll(arr1, 2)

array([3, 4, 1, 2, 3])

In [27]:
arr1

array([1, 2, 3, 3, 4])

In [29]:
np.diag(arr1) # creating a diagonal matrix

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

# Numpy - Binary Operations.

In [30]:
arr1 = np.random.randint(1,10,(3,4))

In [31]:
arr2 = np.random.randint(1,10,(3,4))

In [32]:
arr1

array([[9, 9, 8, 8],
       [6, 4, 4, 6],
       [5, 8, 8, 3]])

In [33]:
arr2

array([[8, 4, 9, 7],
       [2, 5, 4, 5],
       [6, 6, 4, 9]])

In [35]:
arr1 + arr2 # Performing Binary sum

array([[17, 13, 17, 15],
       [ 8,  9,  8, 11],
       [11, 14, 12, 12]])

In [36]:
arr1 / arr2

array([[1.125     , 2.25      , 0.88888889, 1.14285714],
       [3.        , 0.8       , 1.        , 1.2       ],
       [0.83333333, 1.33333333, 2.        , 0.33333333]])

In [37]:
arr1 - arr2

array([[ 1,  5, -1,  1],
       [ 4, -1,  0,  1],
       [-1,  2,  4, -6]])

In [38]:
arr1%arr2

array([[1, 1, 8, 1],
       [0, 4, 0, 1],
       [5, 2, 0, 3]])

In [39]:
arr1 ** arr2

array([[ 43046721,      6561, 134217728,   2097152],
       [       36,      1024,       256,      7776],
       [    15625,    262144,      4096,     19683]])

In [40]:
arr1 & arr2

array([[8, 0, 8, 0],
       [2, 4, 4, 4],
       [4, 0, 0, 1]])

In [41]:
~arr1

array([[-10, -10,  -9,  -9],
       [ -7,  -5,  -5,  -7],
       [ -6,  -9,  -9,  -4]])

In [42]:
arr1 | arr2

array([[ 9, 13,  9, 15],
       [ 6,  5,  4,  7],
       [ 7, 14, 12, 11]])

# Numpy - String Functions.

In [44]:
arr = np.array(['Tarun','kumar'])

In [45]:
arr

array(['Tarun', 'kumar'], dtype='<U5')

In [46]:
np.char.upper(arr)

array(['TARUN', 'KUMAR'], dtype='<U5')

In [47]:
np.char.title(arr)

array(['Tarun', 'Kumar'], dtype='<U5')

In [48]:
np.char.capitalize(arr)

array(['Tarun', 'Kumar'], dtype='<U5')

# Numpy - Mathematical Fuctions.

In [49]:
arr1 

array([[9, 9, 8, 8],
       [6, 4, 4, 6],
       [5, 8, 8, 3]])

In [51]:
np.sin(arr1)

array([[ 0.41211849,  0.41211849,  0.98935825,  0.98935825],
       [-0.2794155 , -0.7568025 , -0.7568025 , -0.2794155 ],
       [-0.95892427,  0.98935825,  0.98935825,  0.14112001]])

In [53]:
np.cos(arr1)

array([[-0.91113026, -0.91113026, -0.14550003, -0.14550003],
       [ 0.96017029, -0.65364362, -0.65364362,  0.96017029],
       [ 0.28366219, -0.14550003, -0.14550003, -0.9899925 ]])

In [54]:
np.tan(arr1)

array([[-0.45231566, -0.45231566, -6.79971146, -6.79971146],
       [-0.29100619,  1.15782128,  1.15782128, -0.29100619],
       [-3.38051501, -6.79971146, -6.79971146, -0.14254654]])

In [55]:
# We can use any mathematical operations according to their need.

In [56]:
np.tanh(arr1)

array([[0.99999997, 0.99999997, 0.99999977, 0.99999977],
       [0.99998771, 0.9993293 , 0.9993293 , 0.99998771],
       [0.9999092 , 0.99999977, 0.99999977, 0.99505475]])

In [57]:
np.log10(arr1)

array([[0.95424251, 0.95424251, 0.90308999, 0.90308999],
       [0.77815125, 0.60205999, 0.60205999, 0.77815125],
       [0.69897   , 0.90308999, 0.90308999, 0.47712125]])

In [58]:
np.exp(arr1)

array([[8103.08392758, 8103.08392758, 2980.95798704, 2980.95798704],
       [ 403.42879349,   54.59815003,   54.59815003,  403.42879349],
       [ 148.4131591 , 2980.95798704, 2980.95798704,   20.08553692]])

In [60]:
np.power(arr1,2)

array([[81, 81, 64, 64],
       [36, 16, 16, 36],
       [25, 64, 64,  9]])

In [61]:
np.sqrt(arr1)

array([[3.        , 3.        , 2.82842712, 2.82842712],
       [2.44948974, 2.        , 2.        , 2.44948974],
       [2.23606798, 2.82842712, 2.82842712, 1.73205081]])

In [62]:
np.mean(arr1)

6.5

In [63]:
np.median(arr1)

7.0

In [66]:
np.std(arr1)

2.0207259421636903

In [69]:
# np.mod(arr1,2)

array([[1, 1, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 1]])

In [71]:
arr1

array([[9, 9, 8, 8],
       [6, 4, 4, 6],
       [5, 8, 8, 3]])

In [72]:
np.min(arr1)

3

In [73]:
np.max(arr1)

9

In [74]:
np.var(arr1)

4.083333333333333